# Site settings
title: Sidharth's Development Log
email: sidharth [at] fafadiatech [dot] com
description: > # this means to ignore newlines until "baseurl:"
  Sidharth is an Entrepreneur passionate about Python and Mobile Technologies. 
  Since 2009 he has been running Fafadia Tech which is based in Mumbai.
  Sidharth holds an MS Degree from USC. He is passionate about Algorithms, Data Mining and Artificial Intelligence.
  Recently he has been playing around with Arduino and RaspberryPi
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sidharthshah.github.io" # the base hostname & protocol for your site
twitter_username: iamsidd
github_username:  sidharthshah

# Build settings
markdown: kramdown
